Repository geoschem/GCClassic, pull requests merged in 2024-03, with the labels that each got.

#52 Now use short submodule names in .gitmodules
  .gitmodules
  CHANGELOG.md
Labels: no-diff-to-benchmark, bugfix

#50 Add GitHub action for compile-only integration tests
  .github/workflows/gcclassic-compile-tests.yml
  CHANGELOG.md
Labels: feature, no-diff-to-benchmark, testing / benchmarking

#53 Remove obsolete options from CH4 menu in geoschem-config.rst
  CHANGELOG.md
  docs/source/gcclassic-user-guide/geoschem-config.rst
Labels: documentation
